apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: june13test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june13test
  name: june13test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
