apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: june13test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: june13test
  name: june13test
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: june13test
